# Generated by Django 2.0 on 2017-12-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='板块名称')),
                ('desc', models.CharField(max_length=100, verbose_name='板块描述')),
                ('manager_name', models.CharField(max_length=100, verbose_name='板块管理员名称')),
                ('stetus', models.IntegerField(choices=[(0, '正常'), (1, '删除')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
            },
        ),
    ]
