# Generated by Django 2.0 on 2017-12-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='stetus',
            new_name='status',
        ),
    ]
